name = "rinawarptech"
pages_build_output_dir = "./apps/website/dist"
compatibility_date = "2025-12-08"

[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "dff80fe842ef4fba8bfca23fa87069db"

[[kv_namespaces]]
binding = "PRICING_KV"
id = "1b91a65e297040fdb823d17cd124adc6"

[[kv_namespaces]]
binding = "BILLING_KV"
id = "84d0fc93567e432d94b04b30e0b89e85"
