name = "rinawarp-updates"
main = "src/worker.js"
compatibility_date = "2024-12-15"

[[r2_buckets]]
binding = "R2"
bucket_name = "rinawarp-updates"

[vars]
ENVIRONMENT = "production"
UPDATES_VERSION = "0.4.0"