directories:
  output: release
  buildResources: build
productName: Rinawarp Terminal Pro
appId: com.rinawarp.terminalpro
files:
  - filter:
      - dist/
      - electron/
      - scripts/
      - package.json
win:
  target:
    - nsis
    - portable
  artifactName: ${productName}-${version}-win-${arch}.${ext}
electronVersion: 38.4.0
